import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import { Grid } from "@mui/material";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Grid
            container
            direction="row"
            justifyContent="center"
            alignItems="center"
            maxWidth="xl"
            sx={{ mx: "auto", marginTop: 10 }}
          >
            {children}
          </Grid>
        </Providers>
      </body>
    </html>
  );
}
